### PR TITLE
fix: Upgrade dependencies and replace obsolete code

### PR DESCRIPTION
**Pull request by Haider8**
The app is now up to date and in running condition

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Remove .idea folder

**Comment by iamareebjamal** [comment]
Wasn't it working before?

**Comment by Haider8** [comment]
> Wasn't it working before?

No. There was obsolete code errors.

**Comment by iamareebjamal** [comment]
Not about compilation. Wasn't app from Google Play working?

**Comment by Haider8** [comment]
No warning from google play

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
